Fixed compile error for --enable-debug on non-Linux
On BSD and Darwin and other non-Linux, --enable-debug compilation
was producing the following error:

---

  sync.cpp:36:27: error: no member named 'lexical_cast' in namespace 'boost'
      uint64_t tid = boost::lexical_cast<uint64_t>(boost::this_thread::get_id());
                   ~~~~~~~^
  sync.cpp:36:40: error: unexpected type name 'uint64_t': expected expression
      uint64_t tid = boost::lexical_cast<uint64_t>(boost::this_thread::get_id());
                                       ^
  2 errors generated.

---

I tried fixing this by #including the requisite lexical_cast header for
boost, but that produced a runtime error due to an uncaught exception on
Darwin (bad_lexical_cast) -- presumably the thread-id on Darwin cannot
be lexically cast to int.

There is no guaranteed way to turn a std::thread::id (or boost::thread::id)
into an int save for hashing it using std::hash. So we do that for the
non-linux case, and compilation succeeds and bitcoind runs ok.