Add a missing atomic include
This prevent this error in Ubuntu xenial and trusty while compling bitcoin-qt:

In file included from qt/modaloverlay.cpp:5:0:
qt/modaloverlay.h:42:10: error: ‘atomic’ in namespace ‘std’ does not name a template type
     std::atomic<int> bestBlockHeight{0}; // best known height (based on the headers)
                   ^